ALTER TABLE disruptions ADD COLUMN IF NOT EXISTS confidence FLOAT;
ALTER TABLE disruptions ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE disruptions ADD COLUMN IF NOT EXISTS start_time TIMESTAMP;
ALTER TABLE disruptions ADD COLUMN IF NOT EXISTS end_time TIMESTAMP;
ALTER TABLE disruptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
