-- Expand zone coverage beyond the initial 12 demo zones
INSERT INTO zones (name, city, state, risk_rating) VALUES
('Anna Nagar', 'Chennai', 'Tamil Nadu', 0.41),
('T Nagar', 'Chennai', 'Tamil Nadu', 0.44),
('Adyar', 'Chennai', 'Tamil Nadu', 0.39),
('Thoraipakkam', 'Chennai', 'Tamil Nadu', 0.46),
('Sholinganallur', 'Chennai', 'Tamil Nadu', 0.47),
('Porur', 'Chennai', 'Tamil Nadu', 0.43),
('Electronic City', 'Bangalore', 'Karnataka', 0.41),
('HSR Layout', 'Bangalore', 'Karnataka', 0.40),
('Marathahalli', 'Bangalore', 'Karnataka', 0.45),
('Yelahanka', 'Bangalore', 'Karnataka', 0.37),
('Jayanagar', 'Bangalore', 'Karnataka', 0.39),
('Rajajinagar', 'Bangalore', 'Karnataka', 0.38),
('Powai', 'Mumbai', 'Maharashtra', 0.43),
('Lower Parel', 'Mumbai', 'Maharashtra', 0.49),
('Goregaon', 'Mumbai', 'Maharashtra', 0.44),
('Chembur', 'Mumbai', 'Maharashtra', 0.46),
('Thane West', 'Mumbai', 'Maharashtra', 0.42),
('Navi Mumbai', 'Mumbai', 'Maharashtra', 0.40),
('Connaught Place', 'Delhi', 'Delhi', 0.52),
('Saket', 'Delhi', 'Delhi', 0.47),
('Dwarka', 'Delhi', 'Delhi', 0.45),
('Rohini', 'Delhi', 'Delhi', 0.44),
('Lajpat Nagar', 'Delhi', 'Delhi', 0.48),
('Noida Sector 62', 'Noida', 'Uttar Pradesh', 0.46),
('Gomti Nagar', 'Lucknow', 'Uttar Pradesh', 0.36),
('Hazratganj', 'Lucknow', 'Uttar Pradesh', 0.38),
('Koregaon Park', 'Pune', 'Maharashtra', 0.37),
('Hinjewadi', 'Pune', 'Maharashtra', 0.41),
('Baner', 'Pune', 'Maharashtra', 0.39),
('Bopal', 'Ahmedabad', 'Gujarat', 0.35),
('Navrangpura', 'Ahmedabad', 'Gujarat', 0.36),
('Salt Lake', 'Kolkata', 'West Bengal', 0.42),
('Park Street', 'Kolkata', 'West Bengal', 0.45),
('Gachibowli', 'Hyderabad', 'Telangana', 0.40),
('Madhapur', 'Hyderabad', 'Telangana', 0.43),
('Banjara Hills', 'Hyderabad', 'Telangana', 0.41)
ON CONFLICT (name) DO NOTHING;
